# Generated by Django 4.0.3 on 2022-04-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('num_admin', models.IntegerField(default='0')),
                ('entreprise', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
