# Generated by Django 4.0.3 on 2022-05-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_admin_profile_pic_empl_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(blank=True, default='2.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empl',
            name='profile_pic',
            field=models.ImageField(blank=True, default='2.png', null=True, upload_to=''),
        ),
    ]
