# Generated by Django 4.0.3 on 2022-05-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_admin_email_admin_first_name_admin_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='email',
            new_name='email1',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='last_name',
            new_name='lname',
        ),
    ]
