# Generated by Django 4.0.3 on 2022-05-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_rename_email_admin_email1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='empl',
            name='email1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empl',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empl',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
